- uses: gradle/actions/setup-gradle@v4
  with:
    validate-wrappers: true

- name: Make gradlew executable
  run: chmod +x ./gradlew

- name: Show projects
  run: ./gradlew projects

- name: Build debug APK
  run: ./gradlew clean :app:assembleDebug --stacktrace --info

- name: Upload APK
  uses: actions/upload-artifact@v4
  with:
    name: CalculatorApp-Debug-APK
    path: app/build/outputs/**/*.apk
    if-no-files-found: error
