name: Build Android APK

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Show Gradle projects and tasks
        run: |
          ./gradlew -v
          ./gradlew projects
          ./gradlew :app:tasks --all

      - name: Build debug APK
        run: ./gradlew clean :app:assembleDebug --stacktrace --info

      - name: List outputs
        run: |
          echo "== app/build/outputs =="
          ls -R app/build/outputs || true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: CalculatorApp-Debug-APK
          path: |
            app/build/outputs/apk/**/*.apk
            app/build/outputs/**/*.apk
          if-no-files-found: error
