name: Build Android APK

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          sdkmanager --licenses <<< "y"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          validate-wrappers: true

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Show Gradle projects and tasks
        run: |
          ./gradlew projects
          ./gradlew :app:tasks --all

      - name: Build debug APK
        run: ./gradlew clean :app:assembleDebug --stacktrace --info --warning-mode all

      - name: List build outputs
        run: |
          echo "== app/build =="
          ls -R app/build || true
          echo "== app/build/outputs =="
          ls -R app/build/outputs || true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: CalculatorApp-Debug-APK
          path: |
            app/build/outputs/apk/**/*.apk
            app/build/**/*.apk
          if-no-files-found: error
