name: Build Android APK

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Helpful diagnostics so we know Gradle sees the Android app
      - name: Show Gradle projects and tasks
        run: |
          ./gradlew -v
          ./gradlew projects
          ./gradlew tasks --all

      # Build the debug APK for the app module explicitly
      - name: Build debug APK
        run: ./gradlew :app:assembleDebug --stacktrace

      # Upload any debug APKs found under app/build/outputs
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CalculatorApp-Debug-APK
          path: app/build/outputs/**/*.apk
          if-no-files-found: error
